#ifndef __ERRORS_H__
#define __ERRORS_H__

#define ERR_DOMAIN 100
#define ERR_NULL_POINTER 101
#define ERR_INPUT_NUMBER 102
#define ERR_NOT_FOUND 103
#define ERR_ALREADY_EXISTS 104
#define ERR_MENU_KEY_INPUT 105
#define ERR_OPEN_FILE 110
#define ERR_CLOSE_FILE 111
#define ERR_WRITING_FILE 112
#define ERR_READING_VALUE 113

#endif // __ERRORS_H__
