#ifndef __ERRORS_H__
#define __ERRORS_H__

#define ERR_MEMORY_ALLOCATION 100
#define ERR_LONGINT_CREATE 101
#define ERR_LONGINT_POINTS_NULL 102
#define ERR_PARSING_BIGFLOAT_STR 103
#define ERR_EMPTY_MANTISSA 104
#define ERR_TOO_MANY_DIGITS 105
#define ERR_NO_INFO 106
#define ERR_CLOSING_FILE 107
#define ERR_NO_CHARACTERS_READ 108

#endif // __ERRORS_H__

